eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
spring:
  application:
    name: auth-service
application:
  config:
    auth-service-url: http://localhost:8088/auth