server :
  port : 9999
eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
      filter:
        prefix-path:
          enabled: true
        strip-prefix:
          enabled: true
            -path = /api



