eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
spring:
  cloud:
    gateway:
      routes:
        -   id: auth-service
            predicates:
              - Path=/api/auth/**
            uri: /api/auth/
