eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
spring:
  application:
    name: zuul-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          predicates:
      routes:
        -   id: auth-service
            uri: http://localhost:/8088
            predicates:
              - Path=/auth/**
    config:
      discovery:
        service-id: zuul-service

