eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: zuul-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        -   id: auth-service
            uri: http://localhost:/8088
            predicates:
              - Path=/auth/**
              - Path=/**
    config:
      discovery:
        service-id: zuul-service

